services:
  multitech-mariadb-server:
    image: mariadb:latest
    container_name: multitech-mariadb-server
    networks:
      - multitech-common-network
    environment:
      - MARIADB_ROOT_PASSWORD=a-nice-admin-password
      - MARIADB_USER=mariadbadmin
      - MARIADB_PASSWORD=a-nice-admin-password
      - MARIADB_DATABASE=multitechdb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  multitech-common-network:
    external: true
