services:
  multitech-oracleenterprise-server:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: multitech-oracleenterprise-server
    networks:
      - multitech-common-network
    environment:
      - ORACLE_PWD=A-nice-admin-password-1234!
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./data:/opt/oracle/oradata
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "echo exit | sqlplus -S system/A-nice-admin-password-1234!@localhost:1521/ORCLCDB",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  multitech-common-network:
    external: true
