services:
  multitech-postgresql-server:
    image: postgres:latest
    container_name: multitech-postgresql-server
    networks:
      - multitech-common-network
    environment:
      - POSTGRES_USER=postgresqladmin
      - POSTGRES_PASSWORD=a-nice-admin-password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresqladmin"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  multitech-common-network:
    external: true
